/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package problem4;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import com.Teacher;
import com.Student;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
		EntityManagerFactory emf = Persistence.createEntityManagerFactory("TeacherPU");
		EntityManager entitymanager = emf.createEntityManager();
		Teacher teach = new Teacher();
		teach.setTeacherId(1);
		teach.setTeacherName("Kvr Prasad");
		teach.setSubject("PSOC");
		
		List<Student> mylist = new ArrayList<Student>();
		mylist.add(new Student("Jaya", "8th semester", teach));
		mylist.add(new Student("Vidya", "7th semester", teach));
		mylist.add(new Student("Lakshmi", "6th semester", teach));
		mylist.add(new Student("Prasanna", "5th semester", teach));
		teach.setList(mylist);
		
		entitymanager.getTransaction().begin();
		entitymanager.persist(teach);
		entitymanager.flush();
		entitymanager.getTransaction().commit();
	}
}